apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-volume
    namespace: crypto-recommendation-service
spec:
    storageClassName: standard
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/tmp/prices"
        type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-claim
    namespace: crypto-recommendation-service
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard